### ISSUE TITLE
[Feature] Setting for default Worktree location

### ISSUE THREAD

**Issue by bjmi** [zielu/GitWorktree#10]
It would be great if one could specify the default location when *Add Worktree*  command is executed. In my case I'd like to specify a different location than `C:\dev\git-repos`.
Alternatively the *Location:* field could show the last used location.
![image](https://github.com/user-attachments/assets/f03c4d34-7df7-4357-903e-1ac82375b965)
Thanks in advance

**Comment by zielu** [comment]
Hi, I agree. How it works now has room for improvement. I'll add setting for default location and if that one will be empty then parent of last used location and some additional fallbacks.

**Comment by zielu** [comment]
Done in 1.0.8

<img width="835" alt="image" src="https://github.com/user-attachments/assets/42da1a4d-1469-49a2-9092-3e2383d6653f">

If location is not set then use last location in which worktree was created, if not present then use platform fallback.

**Comment by bjmi** [comment]
Great thank you very much.
Could you still add a small description text or tooltip in the settings that explains the implemented behavior?
