### ISSUE TITLE
[BUG] IDE settings can no longer be opened after update to v1.0.8+231

### ISSUE THREAD

**Issue by dw-0** [zielu/GitWorktree#11]
**Describe the bug**
I updated to v1.0.8+231 just a moment ago. I noticed, that i cannot open my IDE settings for Intellij IDEA 2024.2.3 anymore.
Disabling the plugin lets me open the settings again.

**To Reproduce**
1. Update from 1.0.7+231
2. Open IDE
3. Try to open the settings menu either via `File -> Settings` or your preferred shortcut.

**Expected behavior**
The IDE settings window to open.

**Plugin version**
1.0.8+231

**IDE version**
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024

**Comment by zielu** [comment]
Hi, I've taken down 1.0.8. As a workaround plugin can be removed from welcome screen and 1.0.7 can be reinstalled then.

**Comment by zielu** [comment]
Done in 1.0.9

**Comment by niklaas** [comment]
Thanks for fixing this quickly. This bug also caused the Actions menu to no longer show any results when searching for an action.

I don't know the intricacies but I find it impressive that a bug in a plugin can make the entire IDE useless. Maybe it's worth escalating this to Jetbrains.

**Comment by zielu** [comment]
Yes I will create a ticket for them. Root cause was missing text resource file. IDE has handling for missing resource keys, but it looks like whole file missing is not really covered.

**Comment by niklaas** [comment]
Appreciated, thank you!
