### ISSUE TITLE
Deleting a freshly created worktree crashes

### ISSUE THREAD

**Issue by palobern** [zielu/GitWorktree#6]
**Describe the bug**
Deleting of worktree crashes

**To Reproduce**
1. create a new worktree (at the same level as the project directory is)
2. go to tab Worktree, select created worktree, right click and delete. (Checkboxes unchecked). Click Yes
3. it crashes with java.lang.IllegalArgumentException: Collection is empty
	at java.base/java.util.EnumSet.copyOf(EnumSet.java:175)
	at zielu.worktree.f.a.g.run(g.java:15)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)

**Expected behavior**
Worktree should be deleted

**Plugin version**
1.0.2+231

**IDE version**
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation

**Comment by zielu** [comment]
Hi, I'll fix it later today.

**Comment by zielu** [comment]
Done in 1.0.3+231
