### ISSUE TITLE
[BUG] Changing Switch Worktree Keyboard Shortcut doesn't persist

### ISSUE THREAD

**Issue by chrismo** [zielu/GitWorktree#7]
**Describe the bug**
If I change the Switch Worktree keyboard shortcut in Keymap, it isn't retained between restarts of RubyMine.

I already have Shift+Cmd+W mapped to Close All Windows

**To Reproduce**
1. Open Settings | Keymap
2. Locate the Switch Worktree command
3. Remove the default keyboard shortcut (mac: Shift+Cmd+W)
4. Add a new one (Shift+Cmd+T)
5. Close IDE
6. Re-open IDE
7. Shortcut has reverted to the default

**Expected behavior**
I expect the altered Keymap to persist between restarts of the IDE

**Plugin version**
1.0.3+231

**IDE version**
RubyMine 2023.3.2
Build #RM-233.13135.91, built on December 19, 2023
Licensed to Chris Morris
You have a perpetual fallback license for this version.
Subscription is active until April 27, 2025.
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
  database.snapshots.auto=false
Non-Bundled Plugins:
  com.aquasecurity.plugins.intellij-Trivy (1.5.0)
  net.sjrx.intellij.plugins.systemdunitfiles (223.231217.132)
  com.4lex4.intellij.solarized (2.4.0)
  org.intellij.plugins.hcl (233.13135.65)
  org.toml.lang (233.13135.67)
  com.andrewbrookins.wrap_to_column (1.8.0)
  com.intellij.ideolog (222.2.0.0)
  name.kropp.intellij.makefile (233.13135.65)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  com.intellij.mermaid (0.0.18+IJ.232)
  org.asciidoctor.intellij.asciidoc (0.41.6)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  zielu.gitworktree (1.0.3+231)
  ru.adelf.idea.dotenv (2023.3)

**Comment by zielu** [comment]
Hi, I tried to reproduce this but no luck. Could you check IDE logs if there are any errors in there?

**Comment by chrismo** [comment]
> Hi, I tried to reproduce this but no luck. Could you check IDE logs if there are any errors in there?

Ah, interesting. Ok, I'll dig some more on my side and see what I can find out. Maybe also I missed a step.

I also have settings sync turned on so changes (including Keymap) propagate between machines where I have RubyMine installed. So - maybe that's a necessary part of this? And maybe it's not a bug at all with your plugin, but something I did on my end.

**Comment by chrismo** [comment]
I tried this again today, ensuring I just had one project open, and closed RubyMine as soon as I'd made the Keymap change, and it persisted this time!

So - maybe there's some weird combo here that can set this up, but I'd reckon any issues here may be generally with the IDE, I wouldn't think your code would have anything unusual in terms of a default Keymap keyboard shortcut.

Thx for your feedback on this.
